### PR TITLE
Feat: Route reference for file manager to create a new empty file

### PR DESCRIPTION
**Pull request by giopalma**
https://github.com/MCSManager/UI/pull/82

**IMPORTANT**: You have to add an error in case a file already exists. Unfortunately I didn't quite understand how errors work, so I wasn't able to fix it, sorry.

### CODE REVIEW

**Comment by yumao233** [comment]
It is normal to throw an error when creating a file if the file exists. Don't worry.

There seems to be no problem with the code. Have you tested it?

**Comment by giopalma** [comment]
Yes it works all fine. The error is throw in the console but not in the UI

**Comment by yumao233** [comment]
Thank you for your contribution. If you like this project, you can recommend it to your friends and look forward to your next contribution.

**Comment by giopalma** [comment]
Absolutely, awesome project! I'm using it to play with my friends. Now I'm looking at creating the docker images of daemon and panel

**Pull request merged**
